java -jar c:\yui\build\yuicompressor-2.4.2.jar "E:\Mes Projets\ProGameMap\public\css\default.css" -o "E:\Mes Projets\ProGameMap\public\css\default-min.css"
java -jar c:\yui\build\yuicompressor-2.4.2.jar "E:\Mes Projets\ProGameMap\public\css\forum.css" -o "E:\Mes Projets\ProGameMap\public\css\forum-min.css"
java -jar c:\yui\build\yuicompressor-2.4.2.jar "E:\Mes Projets\ProGameMap\public\css\hosting.css" -o "E:\Mes Projets\ProGameMap\public\css\hosting-min.css"
java -jar c:\yui\build\yuicompressor-2.4.2.jar "E:\Mes Projets\ProGameMap\public\css\login.css" -o "E:\Mes Projets\ProGameMap\public\css\login-min.css"
java -jar c:\yui\build\yuicompressor-2.4.2.jar "E:\Mes Projets\ProGameMap\public\css\MooFlow.css" -o "E:\Mes Projets\ProGameMap\public\css\MooFlow-min.css"
java -jar c:\yui\build\yuicompressor-2.4.2.jar "E:\Mes Projets\ProGameMap\public\css\mysql_debug.css" -o "E:\Mes Projets\ProGameMap\public\css\mysql_debug-min.css"
java -jar c:\yui\build\yuicompressor-2.4.2.jar "E:\Mes Projets\ProGameMap\public\css\onglet.css" -o "E:\Mes Projets\ProGameMap\public\css\onglet-min.css"
java -jar c:\yui\build\yuicompressor-2.4.2.jar "E:\Mes Projets\ProGameMap\public\css\police.css" -o "E:\Mes Projets\ProGameMap\public\css\police-min.css"
java -jar c:\yui\build\yuicompressor-2.4.2.jar "E:\Mes Projets\ProGameMap\public\css\profil.css" -o "E:\Mes Projets\ProGameMap\public\css\profil-min.css"
java -jar c:\yui\build\yuicompressor-2.4.2.jar "E:\Mes Projets\ProGameMap\public\css\setup.css" -o "E:\Mes Projets\ProGameMap\public\css\setup-min.css"

